# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 13:21
from __future__ import unicode_literals

import cobra.models.fields.bounded
import cobra.models.fields.foreignkey
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', cobra.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Menu name')),
                ('order', models.IntegerField(verbose_name='Menu order')),
                ('is_used', models.BooleanField(default=False, verbose_name='Menu status')),
            ],
            options={
                'abstract': False,
                'db_table': 'cobra_menu',
            },
        ),
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', cobra.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='Order')),
                ('is_used', models.BooleanField(default=False, verbose_name='Status')),
                ('menu', cobra.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('user', cobra.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'cobra_user_menu',
            },
        ),
    ]
