# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0003_auto_20150306_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlogentry',
            options={'ordering': ('-datetime',)},
        ),
    ]
