# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 03:29
from __future__ import unicode_literals

import cobra.models.fields.bounded
import cobra.models.fields.foreignkey
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDepartment',
            fields=[
                ('id', cobra.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('organization', cobra.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_set', to='organization.Organization')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.OrganizationDepartment')),
            ],
            options={
                'abstract': False,
                'db_table': 'cobra_organization_department',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
