# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 00:41
from __future__ import unicode_literals

import cobra.models.fields.bounded
import cobra.models.fields.foreignkey
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_auto_20160104_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDepartmentMember',
            fields=[
                ('id', cobra.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('department', cobra.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_member_set', to='organization.OrganizationDepartment')),
                ('user', cobra.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'cobra_organization_department_member',
            },
        ),
    ]
