# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organizationdepartmentmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdepartment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
