# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20160106_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdepartment',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
